import React from "react";
import { BottomNav } from "../../components/common";
import "./index.less";

const TradeFees = () => {
  return (
    <div>
      <h2>Swap Fees</h2>
      <p>
        A trade fee is a fee the trader pays to swap a liquidity pool. This fee is charged as a percentage of the value of assets the user swaps in a pool. At genesis, this trade fee is set at 0.3% but can be modified through governance. Half the trade fees generated by a pool are distributed to its liquidity providers, with the other half used to buy-and-burn CMDX tokens. Trade fees on limit orders are only charged once orders are executed.
      </p>

      <BottomNav
        preNavLink="transaction-fees"
        prevNavText="Transaction Fees"
        nextNavLink="paircreation-fees"
        nextNavText="Pair Creation fee"
      />

    </div>
  );
};

export default TradeFees;